"""Add passwords salts and improve security

Revision ID: 6cfd7058cf1c
Revises: 532aebcce76b
Create Date: 2019-07-11 23:54:31.185794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cfd7058cf1c'
down_revision = '532aebcce76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.String(length=64), nullable=False))
    op.add_column('user', sa.Column('reset_token', sa.String(length=16), nullable=True))
    op.add_column('user', sa.Column('salt', sa.String(length=64), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=60), nullable=False))
    op.drop_column('user', 'salt')
    op.drop_column('user', 'reset_token')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
